-- CakeMatch AI Week 2 research storage.
-- Student demo only: do not store names, contact details, account data,
-- private research notes, or any other sensitive or personal information here.

create table if not exists public.research_outputs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  topic text not null,
  target_user text not null,
  market text not null,
  research_goal text not null,
  summary text not null,
  benchmarks jsonb not null,
  competitors jsonb not null,
  risks jsonb not null,
  constraint research_outputs_topic_length
    check (char_length(trim(topic)) between 1 and 160),
  constraint research_outputs_target_user_length
    check (char_length(trim(target_user)) between 1 and 160),
  constraint research_outputs_market_length
    check (char_length(trim(market)) between 1 and 80),
  constraint research_outputs_research_goal_length
    check (char_length(trim(research_goal)) between 1 and 300),
  constraint research_outputs_summary_length
    check (char_length(trim(summary)) between 1 and 5000)
);

comment on table public.research_outputs is
  'CakeMatch AI Week 2 student research snapshots. Do not store sensitive or personal information.';
comment on column public.research_outputs.topic is
  'Research topic only; do not include personal information.';
comment on column public.research_outputs.target_user is
  'General audience description only; do not include names or identifying details.';
comment on column public.research_outputs.summary is
  'Research summary only; do not store private or sensitive notes.';

alter table public.research_outputs enable row level security;

-- These public policies are intentionally broad for the unauthenticated student demo.
-- Add authentication and narrower policies before using this table with real users.
drop policy if exists "Public can insert research outputs" on public.research_outputs;
create policy "Public can insert research outputs"
  on public.research_outputs
  for insert
  to public
  with check (true);

drop policy if exists "Public can view research outputs" on public.research_outputs;
create policy "Public can view research outputs"
  on public.research_outputs
  for select
  to public
  using (true);
